// Morrowgrid Invoice PDF API - single-file Cloudflare Worker, no dependencies.
// POST /v1/invoice  JSON invoice -> PDF bytes
// GET  /health      -> {"ok":true}

const PDF = (() => {
  const esc = (s) => String(s).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)").replace(/[^\x20-\x7E]/g, "?");
  function build(lines) {
    // lines: [{x, y, text, size, bold}]
    let content = "BT\n";
    let curFont = null, curSize = null;
    for (const l of lines) {
      const f = l.bold ? "F2" : "F1";
      if (f !== curFont || l.size !== curSize) { content += `/${f} ${l.size} Tf\n`; curFont = f; curSize = l.size; }
      content += `1 0 0 1 ${l.x} ${l.y} Tm (${esc(l.text)}) Tj\n`;
    }
    content += "ET";
    const objs = [];
    objs[1] = "<< /Type /Catalog /Pages 2 0 R >>";
    objs[2] = "<< /Type /Pages /Kids [3 0 R] /Count 1 >>";
    objs[3] = "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>";
    objs[4] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";
    objs[5] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>";
    objs[6] = `<< /Length ${content.length} >>\nstream\n${content}\nendstream`;
    let pdf = "%PDF-1.4\n";
    const offsets = [0];
    for (let i = 1; i <= 6; i++) { offsets[i] = pdf.length; pdf += `${i} 0 obj\n${objs[i]}\nendobj\n`; }
    const xref = pdf.length;
    pdf += `xref\n0 7\n0000000000 65535 f \n`;
    for (let i = 1; i <= 6; i++) pdf += String(offsets[i]).padStart(10, "0") + " 00000 n \n";
    pdf += `trailer\n<< /Size 7 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
    return new TextEncoder().encode(pdf);
  }
  return { build };
})();

const money = (n, cur) => {
  const v = Number(n) || 0;
  const sym = { USD: "$", EUR: "EUR ", GBP: "GBP ", INR: "INR " }[String(cur || "USD").toUpperCase()] || (cur ? cur + " " : "$");
  return sym + v.toFixed(2);
};

function invoiceLines(inv) {
  const L = [];
  const cur = inv.currency || "USD";
  const seller = inv.seller || {}, buyer = inv.buyer || {};
  L.push({ x: 50, y: 740, text: "INVOICE", size: 26, bold: true });
  if (inv.invoice_number) L.push({ x: 400, y: 740, text: "# " + inv.invoice_number, size: 12, bold: true });
  L.push({ x: 400, y: 722, text: "Date: " + (inv.date || new Date().toISOString().slice(0, 10)), size: 10 });
  if (inv.due_date) L.push({ x: 400, y: 708, text: "Due: " + inv.due_date, size: 10 });
  L.push({ x: 50, y: 690, text: "From", size: 10, bold: true });
  let y = 676;
  for (const t of [seller.name, seller.address, seller.email].filter(Boolean)) { L.push({ x: 50, y, text: t, size: 10 }); y -= 13; }
  L.push({ x: 320, y: 690, text: "Bill To", size: 10, bold: true });
  y = 676;
  for (const t of [buyer.name, buyer.address, buyer.email].filter(Boolean)) { L.push({ x: 320, y, text: t, size: 10 }); y -= 13; }
  y = 600;
  L.push({ x: 50, y, text: "Description", size: 10, bold: true });
  L.push({ x: 380, y, text: "Qty", size: 10, bold: true });
  L.push({ x: 430, y, text: "Unit", size: 10, bold: true });
  L.push({ x: 500, y, text: "Amount", size: 10, bold: true });
  y -= 18;
  let sub = 0;
  for (const it of (inv.items || []).slice(0, 22)) {
    const qty = Number(it.qty) || 1, up = Number(it.unit_price) || 0, amt = qty * up;
    sub += amt;
    L.push({ x: 50, y, text: String(it.description || "Item").slice(0, 55), size: 10 });
    L.push({ x: 380, y, text: String(qty), size: 10 });
    L.push({ x: 430, y, text: money(up, cur), size: 10 });
    L.push({ x: 500, y, text: money(amt, cur), size: 10 });
    y -= 15;
  }
  y -= 10;
  const taxRate = Number(inv.tax_rate) || 0, tax = sub * taxRate / 100, total = sub + tax;
  L.push({ x: 430, y, text: "Subtotal:", size: 10 }); L.push({ x: 500, y, text: money(sub, cur), size: 10 }); y -= 14;
  if (taxRate) { L.push({ x: 430, y, text: `Tax (${taxRate}%):`, size: 10 }); L.push({ x: 500, y, text: money(tax, cur), size: 10 }); y -= 14; }
  L.push({ x: 430, y, text: "Total:", size: 11, bold: true }); L.push({ x: 500, y, text: money(total, cur), size: 11, bold: true });
  if (inv.notes) { L.push({ x: 50, y: 120, text: "Notes: " + String(inv.notes).slice(0, 90), size: 9 }); }
  L.push({ x: 50, y: 40, text: "Generated by Morrowgrid Invoice API", size: 8 });
  return L;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === "/health") return Response.json({ ok: true, service: "morrowgrid-invoice-api" });
    if (url.pathname !== "/v1/invoice") return Response.json({ error: "not_found" }, { status: 404 });
    if (request.method !== "POST") return Response.json({ error: "method_not_allowed", hint: "POST JSON invoice to /v1/invoice" }, { status: 405 });
    if (env.PROXY_SECRET) {
      const s = request.headers.get("X-RapidAPI-Proxy-Secret");
      if (s !== env.PROXY_SECRET) return Response.json({ error: "forbidden", hint: "Access via RapidAPI" }, { status: 403 });
    }
    let inv;
    try { inv = await request.json(); } catch { return Response.json({ error: "invalid_json" }, { status: 400 }); }
    if (!inv || !Array.isArray(inv.items) || inv.items.length === 0)
      return Response.json({ error: "missing_items", hint: "items: [{description, qty, unit_price}] required" }, { status: 400 });
    const pdf = PDF.build(invoiceLines(inv));
    return new Response(pdf, { headers: { "Content-Type": "application/pdf", "Content-Disposition": `attachment; filename="invoice-${inv.invoice_number || "draft"}.pdf"` } });
  },
};
